# Generated by Django 3.2.5 on 2021-07-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.CharField(max_length=50)),
                ('player2', models.CharField(max_length=50)),
                ('game_id', models.IntegerField()),
                ('player1_color_selection', models.CharField(max_length=50)),
                ('player2_color_selection', models.CharField(max_length=50)),
                ('player1_moves', models.IntegerField(default=0)),
                ('player2_moves', models.IntegerField(default=0)),
            ],
        ),
    ]
