# Generated by Django 3.2.5 on 2021-07-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20210714_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='player1_color_selection1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player1_color_selection2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player1_color_selection3',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player1_color_selection4',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player2_color_selection1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player2_color_selection2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player2_color_selection3',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player2_color_selection4',
        ),
        migrations.AddField(
            model_name='game',
            name='player1_color_selection',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='player2_color_selection',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
